name: 'deployer-test'
on: # rebuild any PRs and main branch changes
    pull_request:
    push:
        branches:
            - master

jobs:
    prod: # tests production deployer
        runs-on: ubuntu-latest
        name: a job to try deploying the repo in various places
        steps:
            - name: production
              id: production
              uses: mshanemc/deployer-check-javascript-action@master
